config/routes.rb
Rails.application.routes.draw do
  resources :movies, only: %i[index show] do
    collection do
      get 'search'
    end
  end

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = MovieService.fetch_movies
  end

  def show; end

  def search
    @movies = MovieService.fetch_movies(q: params[:q], year: params[:year])
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title CcMoviesdb
    = csrf_meta_tags

    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'movies-bundle'
  body
    = yield

app/views/movies/_form.html.slim
= form_tag search_movies_path, method: :get
  .row.pb-3
    .col-lg-offset-4.col-lg-8.offset-md-2
      .input-group
        span.input-group-prepend.search-panel
          button.btn.btn-outline-secondary.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
            span#search_concept
              = t('.filter.button')
          #fullyear.dropdown-menu.scrollable-menu
            = hidden_field_tag :year, :year
        = text_field_tag :q, params['q'], class: 'form-control rounded-0', placeholder: "#{ t('.placeholder') }"
        span.input-group-append
          = button_tag(type: "submit", id: 'sendButton', class: 'btn btn-outline-secondary form-control') do
            = t('.search.button')

app/views/movies/index.html.slim
.container.pt-4
  = render 'form'
  - unless @movies.present?
    .d-flex.justify-content-center
      h3
        = t('.keywords.search_term')
  - else
    = react_component("MovieCards", props: @movies.to_json)

app/views/movies/show.html.slim
h1 Movies#show
p Find me in app/views/movies/show.html.slim